# Generated by Django 4.1.7 on 2023-03-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
