# Generated by Django 4.1.3 on 2022-12-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_numberphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='numberPhone',
            field=models.CharField(default='89999999999', max_length=12),
        ),
    ]
