# Generated by Django 4.1.3 on 2022-12-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_numberphone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Дополнение профиля', 'verbose_name_plural': 'Дополнение профиля'},
        ),
    ]
