# Generated by Django 4.1.3 on 2023-01-12 21:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_Brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('Car_Model', models.CharField(max_length=50, verbose_name='Модель')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('PTS', models.CharField(max_length=50, verbose_name='ПТС')),
                ('State_Number', models.CharField(max_length=10, verbose_name='Номер')),
                ('VIN', models.CharField(max_length=17, verbose_name='VIN')),
                ('Color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('Relese_Date', models.DateField(default=datetime.datetime(2023, 1, 12, 21, 16, 59, 274926), verbose_name='Дата выпуска')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
