# Generated by Django 4.1.3 on 2023-02-13 18:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0029_alter_comment_pub_date_alter_feedbacklist_date_and_more'),
        ('accounts', '0008_alter_car_relese_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositionWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.specialistlist')),
                ('Works', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.work')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='Relese_Date',
            field=models.DateField(default=datetime.datetime(2023, 2, 13, 18, 52, 12, 899123), verbose_name='Дата выпуска'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Date', models.DateField(default=datetime.datetime(2023, 2, 13, 18, 52, 12, 900122), verbose_name='Дата начала')),
                ('Cost', models.IntegerField(verbose_name='Стоимость')),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.car')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('CompositionWorks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.compositionworks')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.status')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
