# Generated by Django 4.1.3 on 2023-02-13 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_compositionworks_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Relese_Date',
            field=models.DateField(default=datetime.datetime(2023, 2, 13, 19, 3, 5, 768513), verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Start_Date',
            field=models.DateField(default=datetime.datetime(2023, 2, 13, 19, 3, 5, 769526), verbose_name='Дата начала'),
        ),
    ]
