# Generated by Django 4.1.3 on 2023-02-14 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_car_relese_date_alter_order_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Relese_Date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='car',
            name='VIN',
            field=models.CharField(max_length=20, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Start_Date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
    ]
