# Generated by Django 4.1.3 on 2023-02-14 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_alter_car_relese_date_alter_car_vin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Relese_Date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='car',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
