# Generated by Django 4.1.7 on 2023-03-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_remove_order_car_remove_order_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="middleName",
            field=models.CharField(default="Отчество", max_length=40),
        ),
    ]
