# Generated by Django 4.1.7 on 2023-03-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_profile_middlename"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="addres",
            field=models.CharField(default="Адрес", max_length=200),
        ),
    ]
