# Generated by Django 4.1.7 on 2023-03-25 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_profile_addres"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Тип кузова",
                "verbose_name_plural": "Типы кузова",
                "ordering": ("name",),
            },
        ),
        migrations.AlterField(
            model_name="car",
            name="Relese_Date",
            field=models.CharField(default=0, max_length=4, verbose_name="Год выпуска"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="typeCar",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="car",
                to="accounts.typecar",
            ),
        ),
    ]
