# Generated by Django 4.1.7 on 2023-03-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_typecar_alter_car_relese_date_car_typecar"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="mileage",
            field=models.CharField(default=0, max_length=10, verbose_name="Пробег"),
            preserve_default=False,
        ),
    ]
