# Generated by Django 4.1.7 on 2023-03-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_car_mileage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="Relese_Date",
            field=models.CharField(max_length=10, verbose_name="Год выпуска"),
        ),
    ]
