# Generated by Django 4.1.7 on 2023-03-27 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0020_alter_car_relese_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="author",
        ),
        migrations.AddField(
            model_name="car",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
