# Generated by Django 4.1.7 on 2023-03-27 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0021_remove_car_author_car_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="user",
        ),
        migrations.AddField(
            model_name="car",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
