# Generated by Django 4.1.7 on 2023-04-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_remove_car_user_car_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(
                default="defaultCar.jpg", upload_to="profile_images"
            ),
        ),
    ]
