# Generated by Django 4.1.7 on 2023-04-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_alter_car_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="default.png", upload_to="profile_images"),
        ),
    ]
