# Generated by Django 4.1.3 on 2022-11-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_post_file_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
