# Generated by Django 4.1.3 on 2022-11-22 07:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='SpecialistAdmin',
        ),
    ]
