# Generated by Django 4.1.3 on 2022-11-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
