# Generated by Django 4.1.3 on 2022-11-23 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_feedbacklist_email_feedbacklist_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacklist',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
