# Generated by Django 4.1.3 on 2022-12-22 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_feedbacklist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacklist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 17, 10, 27, 174255)),
        ),
    ]
