# Generated by Django 4.1.3 on 2022-12-22 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_feedbacklist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacklist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 18, 37, 44, 31133)),
        ),
    ]
