# Generated by Django 4.1.3 on 2022-12-24 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_feedbacklist_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Содеражние')),
                ('date', models.DateTimeField(verbose_name='Дата публицации')),
            ],
        ),
        migrations.AlterField(
            model_name='feedbacklist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 24, 22, 12, 43, 850319)),
        ),
    ]
