# Generated by Django 4.1.3 on 2022-12-24 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_feedbacklist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacklist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 24, 22, 15, 34, 623792)),
        ),
    ]
