# Generated by Django 4.1.3 on 2022-12-25 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_feedbacklist_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='feedbacklist',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterModelOptions(
            name='maincart',
            options={'verbose_name': 'Главная станица - Карточки', 'verbose_name_plural': 'Главная станица - Карточки'},
        ),
        migrations.AlterModelOptions(
            name='specialistadmin',
            options={'verbose_name': 'Руководство', 'verbose_name_plural': 'Руководство'},
        ),
        migrations.AlterModelOptions(
            name='specialistlist',
            options={'verbose_name': 'Специалисты', 'verbose_name_plural': 'Специалисты'},
        ),
        migrations.AddField(
            model_name='maincart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 25, 16, 0, 54, 455891)),
        ),
        migrations.AlterField(
            model_name='feedbacklist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 25, 16, 0, 54, 455891)),
        ),
    ]
