# Generated by Django 4.1.3 on 2022-12-25 17:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0022_alter_articles_options_alter_feedbacklist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacklist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 25, 17, 26, 22, 307976)),
        ),
        migrations.AlterField(
            model_name='maincart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 25, 17, 26, 22, 307976)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Комментарий')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 12, 25, 17, 26, 22, 307976), verbose_name='Дата комментария')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.articles')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
