# Generated by Django 4.1.3 on 2023-01-12 21:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0024_alter_comment_pub_date_alter_feedbacklist_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название работы')),
                ('Cost', models.CharField(max_length=50, verbose_name='Модель')),
                ('Execution_Time', models.IntegerField(verbose_name='Время выполнения')),
                ('Warranty', models.IntegerField(verbose_name='Гарантия')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 21, 16, 59, 263299), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='feedbacklist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 21, 16, 59, 263299)),
        ),
        migrations.AlterField(
            model_name='maincart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 21, 16, 59, 262310)),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
