# Generated by Django 4.1.3 on 2023-01-12 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_work_alter_comment_pub_date_alter_feedbacklist_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 21, 19, 16, 919146), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='feedbacklist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 21, 19, 16, 918149)),
        ),
        migrations.AlterField(
            model_name='maincart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 21, 19, 16, 918149)),
        ),
        migrations.AlterField(
            model_name='work',
            name='Cost',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
    ]
