# Generated by Django 4.1.3 on 2023-02-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_order_car_remove_order_client_and_more'),
        ('home', '0032_alter_comment_pub_date_alter_feedbacklist_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
