# Generated by Django 4.1.3 on 2023-02-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_delete_work'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
