# Generated by Django 4.1.7 on 2023-03-13 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0034_alter_comment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialistlist",
            options={
                "verbose_name": "Специалист",
                "verbose_name_plural": "Специалисты",
            },
        ),
    ]
