# Generated by Django 4.1.7 on 2023-03-21 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0021_alter_orderwork_work"),
        ("shop", "0003_alter_category_options_alter_categorywork_options_and_more"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="work",
            index_together=None,
        ),
        migrations.RemoveField(
            model_name="work",
            name="category",
        ),
        migrations.DeleteModel(
            name="CategoryWork",
        ),
        migrations.DeleteModel(
            name="Work",
        ),
    ]
