# Generated by Django 4.1.3 on 2023-02-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compositionorder',
            options={'verbose_name': 'Состав заказов', 'verbose_name_plural': 'Составы заказов'},
        ),
        migrations.RemoveField(
            model_name='compositionorder',
            name='ID_Autopart',
        ),
        migrations.AddField(
            model_name='compositionorder',
            name='ID_Autopart',
            field=models.ManyToManyField(to='order.autopart'),
        ),
    ]
