# Generated by Django 4.1.7 on 2023-03-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_remove_compositionorder_id_typesworks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="Work",
            field=models.ManyToManyField(to="order.typeswork"),
        ),
    ]
