# Generated by Django 4.1.7 on 2023-03-14 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0035_alter_specialistlist_options"),
        ("order", "0004_order_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="Autopart",
            field=models.ManyToManyField(to="order.autopart"),
        ),
        migrations.AddField(
            model_name="order",
            name="Employee",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="home.specialistlist",
            ),
            preserve_default=False,
        ),
    ]
