# Generated by Django 4.1.7 on 2023-03-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_order_autopart_order_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderAutopart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=1)),
                (
                    "autopart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.autopart"
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="order",
            old_name="End_Date",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="Start_Date",
            new_name="start_date",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="Status",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="status",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="typeswork",
            old_name="Execution_Time",
            new_name="execution_Time",
        ),
        migrations.RenameField(
            model_name="typeswork",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="typeswork",
            old_name="Price",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="typeswork",
            old_name="Warranty",
            new_name="warranty",
        ),
        migrations.RemoveField(
            model_name="order",
            name="Autopart",
        ),
        migrations.RemoveField(
            model_name="order",
            name="Cost",
        ),
        migrations.RemoveField(
            model_name="order",
            name="Employee",
        ),
        migrations.RemoveField(
            model_name="order",
            name="ID_CompositionOrder",
        ),
        migrations.RemoveField(
            model_name="order",
            name="Work",
        ),
        migrations.AddField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="CompositionOrder",
        ),
        migrations.AddField(
            model_name="orderautopart",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="order.order"
            ),
        ),
    ]
