# Generated by Django 4.1.7 on 2023-03-16 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0009_remove_orderwork_order_order_work"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="work",
        ),
    ]
