# Generated by Django 4.1.7 on 2023-03-16 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0010_remove_order_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="work",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="order.orderwork",
            ),
            preserve_default=False,
        ),
    ]
