# Generated by Django 4.1.7 on 2023-03-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0011_order_work"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="work",
        ),
        migrations.DeleteModel(
            name="OrderWork",
        ),
        migrations.AddField(
            model_name="order",
            name="work",
            field=models.ManyToManyField(to="order.typeswork"),
        ),
    ]
