# Generated by Django 4.1.7 on 2023-03-17 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0012_remove_order_work_delete_orderwork_order_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="autopart",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="order.autopart",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="count",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="order.status",
            ),
        ),
        migrations.DeleteModel(
            name="OrderAutopart",
        ),
    ]
