# Generated by Django 4.1.7 on 2023-03-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0013_order_autopart_order_count_alter_order_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="autopart",
        ),
        migrations.AddField(
            model_name="order",
            name="autopart",
            field=models.ManyToManyField(to="order.autopart"),
        ),
    ]
