# Generated by Django 4.1.7 on 2023-03-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
        ("order", "0014_remove_order_autopart_order_autopart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="autopart",
            field=models.ManyToManyField(to="shop.autopart"),
        ),
        migrations.DeleteModel(
            name="Autopart",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
