# Generated by Django 4.1.7 on 2023-03-19 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0015_alter_order_autopart_delete_autopart_delete_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="order.status"
            ),
        ),
    ]
