# Generated by Django 4.1.7 on 2023-03-20 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_categorywork_work"),
        ("order", "0019_remove_orderitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderwork",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_work",
                to="shop.work",
            ),
        ),
        migrations.DeleteModel(
            name="TypesWork",
        ),
    ]
