# Generated by Django 4.1.7 on 2023-03-21 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0001_initial"),
        ("order", "0020_alter_orderwork_work_delete_typeswork"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderwork",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_work",
                to="work.work",
            ),
        ),
    ]
