# Generated by Django 4.1.7 on 2023-03-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0021_alter_orderwork_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="car_mileage",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
