# Generated by Django 4.1.7 on 2023-03-29 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0022_order_car_mileage"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="client_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Дата прибытия клиента"
            ),
        ),
    ]
