# Generated by Django 4.1.7 on 2023-03-30 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0023_order_client_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="client_time",
            field=models.TimeField(
                default=datetime.datetime.now, verbose_name="Желаемое время для клиента"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="client_date",
            field=models.DateField(
                default=datetime.datetime.now, verbose_name="Желаемая дата для клиента"
            ),
        ),
    ]
