# Generated by Django 4.1.7 on 2023-03-30 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_remove_car_user_car_author"),
        ("order", "0024_order_client_time_alter_order_client_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ID_Car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.car",
                verbose_name="Автомобиль",
            ),
        ),
    ]
