# Generated by Django 4.1.7 on 2023-04-06 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0025_alter_order_id_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ID_Client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="car_mileage",
            field=models.IntegerField(verbose_name="Пробег"),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="Оплачен"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="order.status",
                verbose_name="Статус",
            ),
        ),
    ]
